# Generated by Django 6.0.4 on 2026-05-11 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_organizationmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('trigger_type', models.CharField(choices=[('contact.created', 'Contato criado'), ('conversation.created', 'Conversa criada'), ('conversation.closed', 'Conversa fechada'), ('message.received', 'Mensagem recebida')], db_index=True, max_length=64)),
                ('trigger_filters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('context', models.JSONField(default=dict)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automations.automation')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('action_type', models.CharField(choices=[('send_message', 'Enviar mensagem'), ('send_template', 'Enviar template'), ('http_request', 'Requisição HTTP'), ('toggle_ai', 'Ativar/desativar IA'), ('add_label', 'Adicionar etiqueta'), ('remove_label', 'Remover etiqueta'), ('wait_delay', 'Aguardar'), ('assign_to_user', 'Atribuir a usuário'), ('close_conversation', 'Fechar conversa')], max_length=64)),
                ('config', models.JSONField(default=dict)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='automations.automation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['organization', 'trigger_type', 'is_active'], name='automations_organiz_83778b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='automationstep',
            unique_together={('automation', 'order')},
        ),
    ]
