# Generated by Django 6.0.4 on 2026-05-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='trigger_type',
            field=models.CharField(choices=[('contact.created', 'Contato criado'), ('conversation.created', 'Conversa criada'), ('conversation.closed', 'Conversa fechada'), ('message.received', 'Mensagem recebida'), ('agent.goal_completed', 'Objetivo do agente cumprido')], db_index=True, max_length=64),
        ),
    ]
