# Generated by Django 6.0.4 on 2026-05-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_alter_automation_trigger_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationstep',
            name='action_type',
            field=models.CharField(choices=[('send_message', 'Enviar mensagem'), ('send_template', 'Enviar template'), ('http_request', 'Requisição HTTP'), ('toggle_ai', 'Ativar/desativar IA'), ('add_label', 'Adicionar etiqueta'), ('remove_label', 'Remover etiqueta'), ('wait_delay', 'Aguardar'), ('assign_to_user', 'Atribuir a usuário'), ('close_conversation', 'Fechar conversa'), ('update_deal_stage', 'Mudar etapa do deal (Pipedrive)')], max_length=64),
        ),
    ]
