# Generated by Django 6.0.4 on 2026-05-18 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0003_alter_automationstep_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationstep',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='automationstep',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='automations.automationstep'),
        ),
        migrations.AlterField(
            model_name='automationstep',
            name='action_type',
            field=models.CharField(choices=[('send_message', 'Enviar mensagem'), ('send_template', 'Enviar template'), ('http_request', 'Requisição HTTP'), ('toggle_ai', 'Ativar/desativar IA'), ('add_label', 'Adicionar etiqueta'), ('condition', 'Condição (Se/Senão)'), ('remove_label', 'Remover etiqueta'), ('wait_delay', 'Aguardar'), ('assign_to_user', 'Atribuir a usuário'), ('close_conversation', 'Fechar conversa'), ('update_deal_stage', 'Mudar etapa do deal (Pipedrive)')], max_length=64),
        ),
    ]
