# Generated by Django 6.0.4 on 2026-05-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0004_automationstep_branch_automationstep_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='variant_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='automationstep',
            name='action_type',
            field=models.CharField(choices=[('send_message', 'Enviar mensagem'), ('send_template', 'Enviar template'), ('http_request', 'Requisição HTTP'), ('toggle_ai', 'Ativar/desativar IA'), ('add_label', 'Adicionar etiqueta'), ('condition', 'Condição (Se/Senão)'), ('remove_label', 'Remover etiqueta'), ('start_automation', 'Iniciar outra automação'), ('wait_delay', 'Aguardar'), ('assign_to_user', 'Atribuir a usuário'), ('close_conversation', 'Fechar conversa'), ('update_deal_stage', 'Mudar etapa do deal (Pipedrive)')], max_length=64),
        ),
    ]
