# Generated by Django 6.0.4 on 2026-05-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0005_automation_variant_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='trigger_type',
            field=models.CharField(choices=[('contact.created', 'Contato criado'), ('conversation.created', 'Conversa criada'), ('conversation.closed', 'Conversa fechada'), ('message.received', 'Mensagem recebida'), ('agent.goal_completed', 'Objetivo do agente cumprido'), ('automation.chained', 'Iniciada por automação')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='automationstep',
            name='action_type',
            field=models.CharField(choices=[('send_message', 'Enviar mensagem'), ('send_template', 'Enviar template'), ('http_request', 'Requisição HTTP'), ('toggle_ai', 'Ativar/desativar IA'), ('switch_agent', 'Trocar agente de IA'), ('add_label', 'Adicionar etiqueta'), ('condition', 'Condição (Se/Senão)'), ('remove_label', 'Remover etiqueta'), ('start_automation', 'Iniciar outra automação'), ('wait_delay', 'Aguardar'), ('assign_to_user', 'Atribuir a usuário'), ('close_conversation', 'Fechar conversa'), ('update_deal_stage', 'Mudar etapa do deal (Pipedrive)')], max_length=64),
        ),
    ]
