# Generated by Django 6.0.4 on 2026-06-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0006_alter_automation_trigger_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='trigger_type',
            field=models.CharField(choices=[('contact.created', 'Contato criado'), ('conversation.created', 'Conversa criada'), ('conversation.closed', 'Conversa fechada'), ('message.received', 'Mensagem recebida'), ('agent.goal_completed', 'Objetivo do agente cumprido'), ('automation.chained', 'Iniciada por automação'), ('api.request', 'Requisição recebida (API)')], db_index=True, max_length=64),
        ),
    ]
