# Generated by Django 6.0.4 on 2026-04-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactannotation'),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='labels.label'),
        ),
    ]
