# Generated by Django 6.0.4 on 2026-04-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pipedrive_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
