# Generated by Django 6.0.4 on 2026-04-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='media_type',
            field=models.CharField(choices=[('text', 'Text'), ('document', 'Document'), ('image', 'Image'), ('audio', 'Audio'), ('sticker', 'Sticker')], default='text', max_length=20),
        ),
    ]
