# Generated by Django 6.0.4 on 2026-04-13 18:52

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='api_key',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
