# Generated by Django 6.0.4 on 2026-04-16 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_aiprovider_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='enabled_tools',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='memory_type',
            field=models.CharField(choices=[('per_contact', 'Por contato'), ('global', 'Global')], default='per_contact', max_length=20),
        ),
        migrations.CreateModel(
            name='AgentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('ready', 'Pronto'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agents.aiagent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
