# Generated by Django 6.0.4 on 2026-04-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_aiagent_enabled_tools_aiagent_memory_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='memory_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
