# Generated by Django 6.0.4 on 2026-04-16 18:51

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_aiagent_memory_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCustomTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('url', models.CharField(max_length=2048)),
                ('headers', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='{}')),
                ('body_template', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_tools', to='agents.aiagent')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('agent', 'name')},
            },
        ),
    ]
