# Generated by Django 6.0.4 on 2026-04-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agentcustomtool'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='follow_up_delay',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='follow_up_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='follow_up_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='max_follow_ups',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
