# Generated by Django 6.0.4 on 2026-04-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_aiagent_follow_up_delay_aiagent_follow_up_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='follow_up_respect_hours',
            field=models.BooleanField(default=False),
        ),
    ]
