# Generated by Django 6.0.4 on 2026-05-12 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_aiagent_follow_up_respect_hours'),
        ('contacts', '0004_contact_pipedrive_person_id'),
        ('conversations', '0014_conversation_conversatio_organiz_35d9cc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='goal_action',
            field=models.CharField(blank=True, choices=[('deactivate_ai', 'Desativar IA'), ('close_conversation', 'Fechar conversa'), ('assign_to_user', 'Atribuir a usuário'), ('trigger_automation', 'Disparar automação')], default=''),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='goal_assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='goal_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='goal_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='goal_final_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='goal_slots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='GoalCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_data', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='agents.aiagent')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_completions', to='conversations.conversation')),
            ],
            options={
                'indexes': [models.Index(fields=['agent', '-created_at'], name='agents_goal_agent_i_33560f_idx')],
            },
        ),
    ]
