# Generated by Django 6.0.4 on 2026-05-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_aiagent_goal_action_aiagent_goal_assign_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='split_max_delay_ms',
            field=models.PositiveIntegerField(default=3500),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='split_messages_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='split_min_delay_ms',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='split_typing_speed_ms_per_char',
            field=models.PositiveIntegerField(default=35),
        ),
    ]
