# Generated by Django 6.0.4 on 2026-05-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_aiagent_split_max_delay_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='accumulate_messages_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='accumulate_window_seconds',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
