# Generated by Django 6.0.4 on 2026-05-18 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_documentchunk'),
        ('automations', '0004_automationstep_branch_automationstep_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='goal_automation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='automations.automation'),
        ),
    ]
