# Generated by Django 6.0.4 on 2026-04-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('operator', 'Operator')], max_length=10),
        ),
    ]
