# Generated by Django 6.0.4 on 2026-04-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_messageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='transcription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='transcription_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
