# Generated by Django 6.0.4 on 2026-04-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_sticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='ai_active',
            field=models.BooleanField(default=False),
        ),
    ]
