# Generated by Django 6.0.4 on 2026-04-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0008_message_scheduled_at_message_scheduled_status'),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='labels.label'),
        ),
    ]
