# Generated by Django 6.0.4 on 2026-04-17 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0009_conversation_labels'),
        ('integrations', '0002_alter_whatsappinstance_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='integrations.whatsappinstance'),
        ),
    ]
