# Generated by Django 6.0.4 on 2026-04-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0010_conversation_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pipedrive_deal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
