# Generated by Django 6.0.4 on 2026-04-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('conversations', '0011_conversation_pipedrive_deal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign'),
        ),
    ]
