# Generated by Django 6.0.4 on 2026-04-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0012_conversation_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='follow_up_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
