# Generated by Django 6.0.4 on 2026-04-27 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_organizationmembership'),
        ('agents', '0008_aiagent_follow_up_respect_hours'),
        ('campaigns', '0001_initial'),
        ('contacts', '0004_contact_pipedrive_person_id'),
        ('conversations', '0013_conversation_follow_up_count_and_more'),
        ('integrations', '0006_webhook_secret'),
        ('labels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization', 'status'], name='conversatio_organiz_35d9cc_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization', '-started_at'], name='conversatio_organiz_c5a408_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_4b968d_idx'),
        ),
    ]
