# Generated by Django 6.0.4 on 2026-05-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0014_conversation_conversatio_organiz_35d9cc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='memory_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
