# Generated by Django 6.0.4 on 2026-05-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0015_conversation_memory_reset_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='agent_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
