# Generated by Django 6.0.4 on 2026-04-22 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_permissiongroup_add_pipedriveintegration_and_more'),
        ('agents', '0006_agentcustomtool'),
        ('contacts', '0004_contact_pipedrive_person_id'),
        ('conversations', '0011_conversation_pipedrive_deal_id'),
        ('integrations', '0004_pipedriveintegration_auto_close_deal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ai_active', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('running', 'Enviando'), ('paused', 'Pausada'), ('finished', 'Concluída'), ('cancelled', 'Cancelada')], default='draft')),
                ('interval_min', models.PositiveIntegerField(default=5)),
                ('interval_max', models.PositiveIntegerField(default=15)),
                ('total_contacts', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.aiagent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.whatsappinstance')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending')),
                ('message_sent', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('error', models.TextField(null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conversations.conversation')),
            ],
            options={
                'unique_together': {('campaign', 'contact')},
            },
        ),
    ]
