# Generated by Django 6.0.4 on 2026-04-08 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_invite'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=255, unique=True)),
                ('instance_api_key', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('connecting', 'Connecting')], default='disconnected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_instances', to='agents.aiagent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_instances', to='accounts.organization')),
            ],
        ),
    ]
