# Generated by Django 6.0.4 on 2026-04-10 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappinstance',
            name='agent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_instance', to='agents.aiagent'),
        ),
    ]
