# Generated by Django 6.0.4 on 2026-04-17 18:42

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_invite_avatar_user_avatar'),
        ('integrations', '0002_alter_whatsappinstance_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipedriveIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', encrypted_model_fields.fields.EncryptedTextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipedrive_integration', to='accounts.organization')),
            ],
        ),
    ]
