# Generated by Django 6.0.4 on 2026-04-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_pipedriveintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipedriveintegration',
            name='auto_close_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipedriveintegration',
            name='auto_create_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipedriveintegration',
            name='deal_pipeline_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipedriveintegration',
            name='deal_stage_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipedriveintegration',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pipedriveintegration',
            name='sync_contacts',
            field=models.BooleanField(default=False),
        ),
    ]
