# Generated by Django 6.0.4 on 2026-04-27 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_assignmentqueue_assignmentqueuemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipedriveintegration',
            name='webhook_secret',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
