# Generated by Django 6.0.4 on 2026-04-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappinstance',
            name='evogo_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
