# Generated by Django 6.0.4 on 2026-04-08 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('can_create_agents', models.BooleanField(default=False)),
                ('can_edit_agents', models.BooleanField(default=False)),
                ('can_delete_agents', models.BooleanField(default=False)),
                ('can_view_conversations', models.BooleanField(default=False)),
                ('can_delete_conversations', models.BooleanField(default=False)),
                ('can_export_conversations', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='permission_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.permissiongroup'),
        ),
    ]
