# Generated by Django 6.0.4 on 2026-04-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_agents',
            field=models.BooleanField(default=False),
        ),
    ]
