# Generated by Django 6.0.4 on 2026-04-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_can_view_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
