# Generated by Django 6.0.4 on 2026-04-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_invite_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
