# Generated by Django 6.0.4 on 2026-04-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_invite_avatar_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='add_pipedriveintegration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='delete_pipedriveintegration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='view_pipedriveintegration',
            field=models.BooleanField(default=False),
        ),
    ]
