# Generated by Django 6.0.4 on 2026-04-22 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_permissiongroup_add_pipedriveintegration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('is_open', models.BooleanField(default=True)),
                ('open_time', models.TimeField(default='09:00')),
                ('close_time', models.TimeField(default='18:00')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='accounts.organization')),
            ],
            options={
                'ordering': ['weekday'],
                'unique_together': {('organization', 'weekday')},
            },
        ),
    ]
