# Generated by Django 6.0.4 on 2026-04-27 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def populate_memberships(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    OrganizationMembership = apps.get_model('accounts', 'OrganizationMembership')

    for user in User.objects.exclude(organization=None):
        OrganizationMembership.objects.get_or_create(
            user=user,
            organization=user.organization,
            defaults={'role': user.role, 'permission_group': user.permission_group}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_businesshours'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.organization')),
                ('permission_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.permissiongroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.RunPython(populate_memberships, migrations.RunPython.noop)
    ]
