# Generated by Django 6.0.4 on 2026-06-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_organizationmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='api_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
